### ISSUE TITLE
Cannot Add Integration

### ISSUE THREAD

**Issue by tempus2016** [emcniece/ha_pdf#8]
When I try to install this, I get the following error:
`<Integration emcniece/ha_pdf> Repository structure for v1.1.2 is not compliant
`

**Comment by HITMIK** [comment]
Hello,

Can you fix it, please? @emcniece

Thanks

**Comment by emcniece** [comment]
Apologies @HITMIK I don't have time to focus on this at the moment. I will happily review any pull requests though! Thank you for your understanding.
